import type {Metadata} from "next";
import {Raleway} from "next/font/google";
import "./globals.css";
import Providers from "@/app/components/(utilities)/providers";
import {ReactNode} from "react";

const raleway = Raleway({
    variable: "--font-raleway",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export interface RootLayoutProps {
    children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
    const {children} = props;

    return (
        <html lang="en" suppressHydrationWarning>
        <head><title></title></head>
        <body className={`${raleway.variable}`}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}
